
/* TODO: I'm not sure why GCC is not already using its builtins, so I'forcing
 *       it to consider them. This is probably NOT a good way to do this, but
 *       should work (unless taking the function address, I guess).
 *
 *       Also, some of these builtins are scary (would need syscalls!)
 *
 * Builtin list: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
 */


#define _exit __builtin__exit
#define alloca __builtin_alloca
#define bcmp __builtin_bcmp
#define bzero __builtin_bzero
#define dcgettext __builtin_dcgettext
#define dgettext __builtin_dgettext
#define dremf __builtin_dremf
#define dreml __builtin_dreml
#define drem __builtin_drem
#define exp10f __builtin_exp10f
#define exp10l __builtin_exp10l
#define exp10 __builtin_exp10
#define ffsll __builtin_ffsll
#define ffsl __builtin_ffsl
#define ffs __builtin_ffs
//#define fprintf_unlocked __builtin_fprintf_unlocked
//#define fputs_unlocked __builtin_fputs_unlocked
#define gammaf __builtin_gammaf
#define gammal __builtin_gammal
#define gamma __builtin_gamma
#define gammaf_r __builtin_gammaf_r
#define gammal_r __builtin_gammal_r
#define gamma_r __builtin_gamma_r
#define gettext __builtin_gettext
#define index __builtin_index
#define isascii __builtin_isascii
#define j0f __builtin_j0f
#define j0l __builtin_j0l
#define j0 __builtin_j0
#define j1f __builtin_j1f
#define j1l __builtin_j1l
#define j1 __builtin_j1
#define jnf __builtin_jnf
#define jnl __builtin_jnl
#define jn __builtin_jn
#define lgammaf_r __builtin_lgammaf_r
#define lgammal_r __builtin_lgammal_r
#define lgamma_r __builtin_lgamma_r
#define mempcpy __builtin_mempcpy
#define pow10f __builtin_pow10f
#define pow10l __builtin_pow10l
#define pow10 __builtin_pow10
//#define printf_unlocked __builtin_printf_unlocked
#define rindex __builtin_rindex
#define scalbf __builtin_scalbf
#define scalbl __builtin_scalbl
#define scalb __builtin_scalb
#define signbit __builtin_signbit
#define signbitf __builtin_signbitf
#define signbitl __builtin_signbitl
#define signbitd32 __builtin_signbitd32
#define signbitd64 __builtin_signbitd64
#define signbitd128 __builtin_signbitd128
#define significandf __builtin_significandf
#define significandl __builtin_significandl
#define significand __builtin_significand
#define sincosf __builtin_sincosf
#define sincosl __builtin_sincosl
#define sincos __builtin_sincos
#define stpcpy __builtin_stpcpy
#define stpncpy __builtin_stpncpy
#define strcasecmp __builtin_strcasecmp
#define strdup __builtin_strdup
#define strfmon __builtin_strfmon
#define strncasecmp __builtin_strncasecmp
#define strndup __builtin_strndup
#define toascii __builtin_toascii
#define y0f __builtin_y0f
#define y0l __builtin_y0l
#define y0 __builtin_y0
#define y1f __builtin_y1f
#define y1l __builtin_y1l
#define y1 __builtin_y1
#define ynf __builtin_ynf
#define ynl __builtin_ynl
#define yn __builtin_yn

#define _Exit __builtin__Exit
#define acoshf __builtin_acoshf
#define acoshl __builtin_acoshl
#define acosh __builtin_acosh
#define asinhf __builtin_asinhf
#define asinhl __builtin_asinhl
#define asinh __builtin_asinh
#define atanhf __builtin_atanhf
#define atanhl __builtin_atanhl
#define atanh __builtin_atanh
#define cabsf __builtin_cabsf
#define cabsl __builtin_cabsl
#define cabs __builtin_cabs
#define cacosf __builtin_cacosf
#define cacoshf __builtin_cacoshf
#define cacoshl __builtin_cacoshl
#define cacosh __builtin_cacosh
#define cacosl __builtin_cacosl
#define cacos __builtin_cacos
#define cargf __builtin_cargf
#define cargl __builtin_cargl
#define carg __builtin_carg
#define casinf __builtin_casinf
#define casinhf __builtin_casinhf
#define casinhl __builtin_casinhl
#define casinh __builtin_casinh
#define casinl __builtin_casinl
#define casin __builtin_casin
#define catanf __builtin_catanf
#define catanhf __builtin_catanhf
#define catanhl __builtin_catanhl
#define catanh __builtin_catanh
#define catanl __builtin_catanl
#define catan __builtin_catan
#define cbrtf __builtin_cbrtf
#define cbrtl __builtin_cbrtl
#define cbrt __builtin_cbrt
#define ccosf __builtin_ccosf
#define ccoshf __builtin_ccoshf
#define ccoshl __builtin_ccoshl
#define ccosh __builtin_ccosh
#define ccosl __builtin_ccosl
#define ccos __builtin_ccos
#define cexpf __builtin_cexpf
#define cexpl __builtin_cexpl
#define cexp __builtin_cexp
#define cimagf __builtin_cimagf
#define cimagl __builtin_cimagl
#define cimag __builtin_cimag
#define clogf __builtin_clogf
#define clogl __builtin_clogl
#define clog __builtin_clog
#define conjf __builtin_conjf
#define conjl __builtin_conjl
#define conj __builtin_conj
#define copysignf __builtin_copysignf
#define copysignl __builtin_copysignl
#define copysign __builtin_copysign
#define cpowf __builtin_cpowf
#define cpowl __builtin_cpowl
#define cpow __builtin_cpow
#define cprojf __builtin_cprojf
#define cprojl __builtin_cprojl
#define cproj __builtin_cproj
#define crealf __builtin_crealf
#define creall __builtin_creall
#define creal __builtin_creal
#define csinf __builtin_csinf
#define csinhf __builtin_csinhf
#define csinhl __builtin_csinhl
#define csinh __builtin_csinh
#define csinl __builtin_csinl
#define csin __builtin_csin
#define csqrtf __builtin_csqrtf
#define csqrtl __builtin_csqrtl
#define csqrt __builtin_csqrt
#define ctanf __builtin_ctanf
#define ctanhf __builtin_ctanhf
#define ctanhl __builtin_ctanhl
#define ctanh __builtin_ctanh
#define ctanl __builtin_ctanl
#define ctan __builtin_ctan
#define erfcf __builtin_erfcf
#define erfcl __builtin_erfcl
#define erfc __builtin_erfc
#define erff __builtin_erff
#define erfl __builtin_erfl
#define erf __builtin_erf
#define exp2f __builtin_exp2f
#define exp2l __builtin_exp2l
#define exp2 __builtin_exp2
#define expm1f __builtin_expm1f
#define expm1l __builtin_expm1l
#define expm1 __builtin_expm1
#define fdimf __builtin_fdimf
#define fdiml __builtin_fdiml
#define fdim __builtin_fdim
#define fmaf __builtin_fmaf
#define fmal __builtin_fmal
#define fmaxf __builtin_fmaxf
#define fmaxl __builtin_fmaxl
#define fmax __builtin_fmax
#define fma __builtin_fma
#define fminf __builtin_fminf
#define fminl __builtin_fminl
#define fmin __builtin_fmin
#define hypotf __builtin_hypotf
#define hypotl __builtin_hypotl
#define hypot __builtin_hypot
#define ilogbf __builtin_ilogbf
#define ilogbl __builtin_ilogbl
#define ilogb __builtin_ilogb
#define imaxabs __builtin_imaxabs
#define isblank __builtin_isblank
#define iswblank __builtin_iswblank
#define lgammaf __builtin_lgammaf
#define lgammal __builtin_lgammal
#define lgamma __builtin_lgamma
#define llabs __builtin_llabs
#define llrintf __builtin_llrintf
#define llrintl __builtin_llrintl
#define llrint __builtin_llrint
#define llroundf __builtin_llroundf
#define llroundl __builtin_llroundl
#define llround __builtin_llround
#define log1pf __builtin_log1pf
#define log1pl __builtin_log1pl
#define log1p __builtin_log1p
#define log2f __builtin_log2f
#define log2l __builtin_log2l
#define log2 __builtin_log2
#define logbf __builtin_logbf
#define logbl __builtin_logbl
#define logb __builtin_logb
#define lrintf __builtin_lrintf
#define lrintl __builtin_lrintl
#define lrint __builtin_lrint
#define lroundf __builtin_lroundf
#define lroundl __builtin_lroundl
#define lround __builtin_lround
#define nearbyintf __builtin_nearbyintf
#define nearbyintl __builtin_nearbyintl
#define nearbyint __builtin_nearbyint
#define nextafterf __builtin_nextafterf
#define nextafterl __builtin_nextafterl
#define nextafter __builtin_nextafter
#define nexttowardf __builtin_nexttowardf
#define nexttowardl __builtin_nexttowardl
#define nexttoward __builtin_nexttoward
#define remainderf __builtin_remainderf
#define remainderl __builtin_remainderl
#define remainder __builtin_remainder
#define remquof __builtin_remquof
#define remquol __builtin_remquol
#define remquo __builtin_remquo
#define rintf __builtin_rintf
#define rintl __builtin_rintl
#define rint __builtin_rint
#define roundf __builtin_roundf
#define roundl __builtin_roundl
#define round __builtin_round
#define scalblnf __builtin_scalblnf
#define scalblnl __builtin_scalblnl
#define scalbln __builtin_scalbln
#define scalbnf __builtin_scalbnf
#define scalbnl __builtin_scalbnl
#define scalbn __builtin_scalbn
#define snprintf __builtin_snprintf
#define tgammaf __builtin_tgammaf
#define tgammal __builtin_tgammal
#define tgamma __builtin_tgamma
#define truncf __builtin_truncf
#define truncl __builtin_truncl
#define trunc __builtin_trunc
#define vfscanf __builtin_vfscanf
#define vscanf __builtin_vscanf
#define vsnprintf __builtin_vsnprintf
#define vsscanf __builtin_vsscanf

#define acosf __builtin_acosf
#define acosl __builtin_acosl
#define asinf __builtin_asinf
#define asinl __builtin_asinl
#define atan2f __builtin_atan2f
#define atan2l __builtin_atan2l
#define atanf __builtin_atanf
#define atanl __builtin_atanl
#define ceilf __builtin_ceilf
#define ceill __builtin_ceill
#define cosf __builtin_cosf
#define coshf __builtin_coshf
#define coshl __builtin_coshl
#define cosl __builtin_cosl
#define expf __builtin_expf
#define expl __builtin_expl
#define fabsf __builtin_fabsf
#define fabsl __builtin_fabsl
#define floorf __builtin_floorf
#define floorl __builtin_floorl
#define fmodf __builtin_fmodf
#define fmodl __builtin_fmodl
#define frexpf __builtin_frexpf
#define frexpl __builtin_frexpl
#define ldexpf __builtin_ldexpf
#define ldexpl __builtin_ldexpl
#define log10f __builtin_log10f
#define log10l __builtin_log10l
#define logf __builtin_logf
#define logl __builtin_logl
#define modfl __builtin_modfl
#define modf __builtin_modf
#define powf __builtin_powf
#define powl __builtin_powl
#define sinf __builtin_sinf
#define sinhf __builtin_sinhf
#define sinhl __builtin_sinhl
#define sinl __builtin_sinl
#define sqrtf __builtin_sqrtf
#define sqrtl __builtin_sqrtl
#define tanf __builtin_tanf
#define tanhf __builtin_tanhf
#define tanhl __builtin_tanhl
#define tanl __builtin_tanl

#define iswalnum __builtin_iswalnum
#define iswalpha __builtin_iswalpha
#define iswcntrl __builtin_iswcntrl
#define iswdigit __builtin_iswdigit
#define iswgraph __builtin_iswgraph
#define iswlower __builtin_iswlower
#define iswprint __builtin_iswprint
#define iswpunct __builtin_iswpunct
#define iswspace __builtin_iswspace
#define iswupper __builtin_iswupper
#define iswxdigit __builtin_iswxdigit
#define towlower __builtin_towlower
#define towupper __builtin_towupper

#define abort __builtin_abort
#define abs __builtin_abs
#define acos __builtin_acos
#define asin __builtin_asin
#define atan2 __builtin_atan2
#define atan __builtin_atan
#define calloc __builtin_calloc
#define ceil __builtin_ceil
#define cosh __builtin_cosh
#define cos __builtin_cos
#define exit __builtin_exit
#define exp __builtin_exp
#define fabs __builtin_fabs
#define floor __builtin_floor
#define fmod __builtin_fmod
//#define fprintf __builtin_fprintf
//#define fputs __builtin_fputs
#define frexp __builtin_frexp
#define fscanf __builtin_fscanf
#define isalnum __builtin_isalnum
#define isalpha __builtin_isalpha
#define iscntrl __builtin_iscntrl
#define isdigit __builtin_isdigit
#define isgraph __builtin_isgraph
#define islower __builtin_islower
#define isprint __builtin_isprint
#define ispunct __builtin_ispunct
#define isspace __builtin_isspace
#define isupper __builtin_isupper
#define isxdigit __builtin_isxdigit
#define tolower __builtin_tolower
#define toupper __builtin_toupper
#define labs __builtin_labs
#define ldexp __builtin_ldexp
#define log10 __builtin_log10
#define log __builtin_log
#define malloc __builtin_malloc
#define memchr __builtin_memchr
#define memcmp __builtin_memcmp
#define memcpy __builtin_memcpy
#define memset __builtin_memset
#define modf __builtin_modf
#define pow __builtin_pow
//#define printf __builtin_printf
//#define putchar __builtin_putchar
//#define puts __builtin_puts
#define scanf __builtin_scanf
#define sinh __builtin_sinh
#define sin __builtin_sin
#define snprintf __builtin_snprintf
#define sprintf __builtin_sprintf
#define sqrt __builtin_sqrt
#define sscanf __builtin_sscanf
#define strcat __builtin_strcat
#define strchr __builtin_strchr
#define strcmp __builtin_strcmp
#define strcpy __builtin_strcpy
#define strcspn __builtin_strcspn
#define strlen __builtin_strlen
#define strncat __builtin_strncat
#define strncmp __builtin_strncmp
#define strncpy __builtin_strncpy
#define strpbrk __builtin_strpbrk
#define strrchr __builtin_strrchr
#define strspn __builtin_strspn
#define strstr __builtin_strstr
#define tanh __builtin_tanh
#define tan __builtin_tan
//#define vfprintf __builtin_vfprintf
//#define vprintf __builtin_vprintf
#define vsprintf __builtin_vsprintf


#define isgreater __builtin_isgreater
#define isgreaterequal __builtin_isgreaterequal
#define isless __builtin_isless
#define islessequal __builtin_islessequal
#define islessgreater __builtin_islessgreater
#define isunordered __builtin_isunordered
#define fpclassify __builtin_fpclassify
#define isfinite __builtin_isfinite
#define isinf_sign __builtin_isinf_sign
#define isnormal __builtin_isnormal
